name: Build UHeadless

on:
  push:
    branches: [ v**/contrib ]
    paths:
      - 'src/**'
      - '.github/workflows/build.yml'
  pull_request:
    branches: [ v**/contrib ]
    paths:
      - 'src/**'
      - '.github/workflows/build.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          6.0.x
          7.0.x

    - uses: actions/cache@v3
      id: cache-nuget-uheadless
      with:
        path: |
          ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-uheadless

    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./src

    - name: Build
      run: dotnet build --no-restore
      working-directory: ./src

    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ./src
